/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\SheenChair.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelChair(props) {
  const { nodes, materials } = useGLTF('/SheenChair.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SheenChair_fabric.geometry} material={materials['fabric Mystere Mango Velvet']} />
      <mesh geometry={nodes.SheenChair_wood.geometry} material={materials['wood Brown']} />
      <mesh geometry={nodes.SheenChair_metal.geometry} material={materials.metal} />
      <mesh geometry={nodes.SheenChair_label.geometry} material={materials.label} position={[-0.001, 0.236, 0.06]} rotation={[-0.087, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/SheenChair.glb')
